const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'Shirt',
      image: '/images/shirt1.jpg',
      price: 60,
      rating: 4.5,
      numRewies: 20,
      countInStock: 12,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'Shirt',
      image: '/images/shirt2.jpg',
      price: 70,
      rating: 4.5,
      numRewies: 20,
      countInStock: 12,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      category: 'Shirt',
      image: '/images/shirt3.jpg',
      price: 80,
      rating: 4.5,
      numRewies: 20,
      countInStock: 12,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      rating: 4.5,
      numRewies: 20,
      countInStock: 12,
      description: 'Smart looking shirt',
    },
    {
      name: 'Fit Pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      rating: 4.5,
      numRewies: 20,
      countInStock: 12,
      description: 'A popular fit pants',
    },
    {
      name: 'Classic Pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 85,
      rating: 4.5,
      numRewies: 20,
      countInStock: 12,
      description: 'A popular pants',
    },
  ],
};
export default data;
